=== ToqaEid/PlayGround/ClientChat/build/classes/View/chat.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="chat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="me">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:int" name="id"/>
                                        <xs:element type="xs:string" name="userName"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="notMe">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="messages">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="message" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:int" name="from"/>
                                        
                                        <xs:element type="xs:string" name="color"/>
                                        <xs:element type="xs:string" name="font"/>
                                        <xs:element type="xs:string" name="senderName"/>
                                        <xs:element type="xs:string" name="text"/>
                    
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ToqaEid/PlayGround/ClientChat/build/classes/View/xmlMessages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?xml-stylesheet type = "text/xsl" href = "view.xsl"?>
<chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="chat.xsd">
    <users>
        <me>
            <id>1</id>
            <userName>marko</userName>
        </me>
        <notMe>
            <name>
                eslam 
            </name>
            <name>
                samy 
            </name>
            <name>
                toqa 
            </name>
        </notMe>
    </users>
    <messages>
        <message>
            <from>1</from>
            
            <color>red</color>
            <font>arial</font>
            <senderName>marko</senderName>
            
            <text>
                el3aaaaaaab
            </text>
        </message>
        <message>
            <from>5</from>
            
            <color>red</color>
            <font>arial</font>
            <senderName>samy</senderName>
           <text>
                hiiiiiiiiiiiii
            </text>
            
        </message>
        <message>
            <from>8</from>
            
            <color>red</color>
            <font>arial</font>
            <senderName>toqa</senderName>
            <text>
                el3ab
            </text>
        </message>
                <message>
            <from>8</from>
            
            <color>white</color>
            <font>verdana</font>
            <senderName>samy</senderName>
            <text>
                loooooooool
            </text>
        </message>
                <message>
            <from>8</from>
            
            <color>red</color>
            <font>arial</font>
            <senderName>eslam</senderName>
            <text>
                la2aaaaaaaaaaaaaa :D :D 
            </text>
        </message>
        <message>
            <from>1</from>
            
            <color>black</color>
            <font>verdana</font>
            <senderName>marko</senderName>
            <text>
                bas ya papa menk leha :D 
            </text>
        </message>
        <message>
            <from>1</from>
            
            <color>black</color>
            <font>verdana</font>
            <senderName>marko</senderName>
            <text>
                wsl:D 
            </text>
        </message>
		<message>
            <from>8</from>
            
            <color>black</color>
            <font>verdana</font>
            <senderName>marko</senderName>
            <text>
                wsl:D 
            </text>
        </message>
		<message>
            <from>1</from>
            
            <color>black</color>
            <font>verdana</font>
            <senderName>marko</senderName>
            <text>
                wslasdfghjgfd:D 
            </text>
        </message>
    </messages>
</chat>
