=== ToqaEid/PlayGround/ClientChat/build/classes/XML/chatSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified">
    <xs:element name="chat" type="chatDetail"/>
    <xs:complexType name="chatDetail">
        <xs:sequence>
            <xs:element name="users" type="users"/>
            <xs:element name="messages" type="Message"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="users">
        <xs:sequence>
            <xs:element name="chatCreatorClient" type="userData"/>
             <xs:element name="otherClient" maxOccurs="unbounded" type="userData"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="userData">
        <xs:sequence>
             <xs:element name="email" type="xs:string"/>
              <xs:element name="userName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
     <xs:complexType name="Message">
        <xs:sequence>
            <xs:element name="msg" maxOccurs="unbounded" type="MsgData"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MsgData">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string"/>
            <xs:element name="date" type="xs:string"/>
            <xs:element name="body" type="xs:string"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="font" type="xs:string"/>
            <xs:element name="size" type="xs:string" default="20"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ToqaEid/PlayGround/ClientChat/ClientJar11/chat.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="chatStyle.xsl" ?>

<chat xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='chatSchema.xsd'>
    <users>
        <chatCreatorClient>
            <email>israa@yahoo.com</email>
            <userName>israa</userName>  
        </chatCreatorClient>
        
        <otherClient>
             <email>toqa@yahoo.com</email>
            <userName>toqa</userName> 
        </otherClient>
         <otherClient>
             <email> </email>
            <userName> </userName> 
        </otherClient>
        
        
    </users>
    <messages>
    <msg>
        <from>israa</from>
        <to>toqa</to>
        <date>1994-11-01</date>
        <body>Hello,toqa</body>
        <color>red</color>
        <font>Arial</font>
        <size>15</size>
    </msg>
     <msg>
        <from>israa</from>
        <to>toqa</to>
        <date>1994-11-01</date>
        <body>are u here!</body>
        <color>red</color>
        <font>Arial</font>
        <size>15</size>
    </msg>
    <msg>
         <from>toqa</from>
        <to>israa</to>
        <date>1994-11-01</date>
        <body>yes,Hello Israa</body>
        <color>red</color>
        <font>Arial</font>
        <size>15</size>
    </msg>
     <msg>
        <from>israa</from>
        <to>toqa</to>
        <date>1994-11-01</date>
        <body>How are u?</body>
        <color>red</color>
        <font>Arial</font>
        <size>15</size>
    </msg>
    
    </messages>
</chat>

=== ToqaEid/PlayGround/ClientChat/ClientJar12/a@gmail.com2017-02-20,10.59.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?><chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd"><users><chatCreatorClient><email>t@t.com</email><userName>israa</userName></chatCreatorClient><otherClient><email>a@gmail.com</email></otherClient></users><messages><msg><from>a@gmail.com</from><to>t@t.com</to><date>2017/02/20 10:58:14</date><body>hi</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>a@gmail.com</from><to>t@t.com</to><date>2017/02/20 10:59:18</date><body>chj</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>t@t.com</from><to>a@gmail.com</to><date>2017/02/20 10:59:26</date><body>dfgh</body><color>#000000</color><font>Times New Roman</font><size></size></msg></messages></chat>

=== ToqaEid/PlayGround/ClientChat/build/classes/XML/t@t.com2017-02-19,12.06.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?><chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd"><users><chatCreatorClient><email>a@gmail.com</email><userName>israa</userName></chatCreatorClient><otherClient><email>t@t.com</email></otherClient></users><messages><msg><from>a@gmail.com</from><to>t@t.com</to><date>2017/02/19 12:06:00</date><body>huhjhdsjkhjf</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>a@gmail.com</from><to>t@t.com</to><date>2017/02/19 12:06:18</date><body>asdff</body><color>#000000</color><font>Times New Roman</font><size></size></msg></messages></chat>

=== ToqaEid/PlayGround/ClientChat/build/classes/XML/m@gmail.com2017-02-19,01.22.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?><chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd"><users><chatCreatorClient><email>t@t.com</email><userName>israa</userName></chatCreatorClient><otherClient><email>m@gmail.com</email></otherClient></users><messages><msg><from>m@gmail.com</from><to>t@t.com</to><date>2017/02/19 01:22:14</date><body>wer</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>m@gmail.com</from><to>t@t.com</to><date>2017/02/19 01:22:26</date><body>wef</body><color>#000000</color><font>Verdana</font><size>40</size></msg><msg><from>t@t.com</from><to>m@gmail.com</to><date>2017/02/19 01:22:31</date><body>fd</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>t@t.com</from><to>m@gmail.com</to><date>2017/02/19 01:22:37</date><body>gfre</body><color>#000000</color><font>Times New Roman</font><size>50</size></msg></messages></chat>

=== ToqaEid/PlayGround/ClientChat/ClientJar12/israa@yahoo.com2017-02-20,11.52.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?>
<chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd">
<users>
<chatCreatorClient>
<email>a@gmail.com</email>
<userName>israa</userName>
</chatCreatorClient>
<otherClient>
<email>israa@yahoo.com</email>
</otherClient>
</users>
<messages>
<msg>
<from>a@gmail.com</from><to>israa@yahoo.com</to><date>2017/02/20 11:50:39</date><body>hi</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>israa@yahoo.com</from><to>a@gmail.com</to><date>2017/02/20 11:50:59</date><body>hi</body><color>#4D66CC</color><font>Times New Roman</font><size>30</size></msg><msg><from>israa@yahoo.com</from><to>a@gmail.com</to><date>2017/02/20 11:51:52</date><body>jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjlodksfldgbthfjlffmdesjrletrklrstkl;er;le;lewioeruteruerjndsfndfgjfwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</body><color>#4D66CC</color><font>Times New Roman</font><size>30</size></msg><msg><from>a@gmail.com</from><to>israa@yahoo.com</to><date>2017/02/20 11:52:20</date><body>dfjgdifgudiofug dofigndfgodfigndfogidfg</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>israa@yahoo.com</from><to>a@gmail.com</to><date>2017/02/20 11:52:32</date><body>jdfsgjsdrsjf</body><color>#4D66CC</color><font>Times New Roman</font><size>30</size></msg></messages></chat>

=== ToqaEid/PlayGround/ClientChat/build/classes/XML/t@t.com2017-02-19,00.31.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?><chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd"><users><chatCreatorClient><email>m@gmail.com</email><userName>israa</userName></chatCreatorClient><otherClient><email>t@t.com</email></otherClient></users><messages><msg><from>m@gmail.com</from><to>t@t.com</to><date>2017/02/19 00:30:25</date><body>hi toqa</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>t@t.com</from><to>m@gmail.com</to><date>2017/02/19 00:30:39</date><body>hello m </body><color>#B36680</color><font>Times New Roman</font><size></size></msg><msg><from>m@gmail.com</from><to>t@t.com</to><date>2017/02/19 00:31:05</date><body>how is your project</body><color>#B31A1A</color><font>Lucida Console</font><size>10</size></msg><msg><from>m@gmail.com</from><to>t@t.com</to><date>2017/02/19 00:31:26</date><body>I am testing it right now </body><color>#B31A1A</color><font>Lucida Console</font><size>40</size></msg></messages></chat>

=== ToqaEid/PlayGround/ClientChat/src/XML/s@s.com2017-02-19,12.56.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?><chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd"><users><chatCreatorClient><email>t@t.com</email><userName>israa</userName></chatCreatorClient><otherClient><email>s@s.com</email></otherClient></users><messages><msg><from>t@t.com</from><to>s@s.com</to><date>2017/02/19 12:57:23</date><body>12345</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>s@s.com</from><to>t@t.com</to><date>2017/02/19 12:56:43</date><body>po9opo</body><color>#000000</color><font>Times New Roman</font><size></size></msg></messages></chat>

=== ToqaEid/PlayGround/ClientChat/build/classes/XML/bebetoo@s7s.com2017-02-19,12.24.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='chatStyle.xsl'?><chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatSchema.xsd"><users><chatCreatorClient><email>toqa@s7s.com</email><userName>israa</userName></chatCreatorClient><otherClient><email>bebetoo@s7s.com</email></otherClient></users><messages><msg><from>toqa@s7s.com</from><to>bebetoo@s7s.com</to><date>2017/02/19 12:24:50</date><body>1234</body><color>#000000</color><font>Times New Roman</font><size></size></msg><msg><from>bebetoo@s7s.com</from><to>toqa@s7s.com</to><date>2017/02/19 12:24:24</date><body>888888888888888</body><color>#000000</color><font>Times New Roman</font><size></size></msg></messages></chat>
